<?php
/**
 * Created by PhpStorm.
 * User: eche
 * Date: 7/2/18
 * Time: 11:10 AM
 */

namespace API\Model;

require_once __DIR__ . "/../../bootstrap.php";


class Image
{

    /*
     * Holds all the parameters passed from the payload
     */
    public $param;

    /*
     * Holds all the texts to be written.
     */
    private $text;

    /*
    * In order to get the right size of box, especially in 
    *occasions that a word wrap is needed, the text has to be 
    *wrapped before using it to make the box.
    */
    private $wrappedHeader;
    private $wrappedBody;
    private $wrappedFooter;

    /*
    * When text is written on a canvas, there will be need
    * generate name for the image file, in order to save it.
    * That will be stored in this property.
    */
    public $randomName;

    /*
    * Holds the image resource being written on. That is the 
    * resource returned by imagecreatetruecolor().
    * Note: this is not the image uploaded by the user, rather
    * an image resource generated by the application. This is 
    * is especially important for writting on a colour canvas.
    */
    public $imageCanvas;

    /*
    * When a user supplies the path to image file to be written
    * it is stored here. 
    */
    private $imagePath;
    private $image;

    /*
    *   Properties to hold the paths to the various font files.
    */
    private $aria;
    private $pacifico;
    private $franchise;
    private $prisma;

    /*
     * Dimensions. If the image resource sent is more 600x600,
     * it will be resized to 600x600.
     */
    private $width = 600;
    private $height = 600;

    /*
     * Image file and resource.
     */
    public $imageSource; // Image file being written on
    private $receivedImages = 'file_storage/images/'; // Location to store the images uploaded by the client


    /*
    * Each text to be written is put inside a bounding box, just slightly bigger
    * than the text itself. The three various texts supplied are
    * stored in these class properties.
    */
    private $headerBox;
    private $bodyBox;
    private $footerBox;

    /*
    * For each text supplied by the user a position has to be
    * assigned. The various positions are stored in these properties.
    */
    private $titlePosition;
    private $bodyPosition;
    private $footerPosition;

    /*
    * An array to hold all the values of colours that can be
    * specified by the user.
    */
    private $colours;
    private $black;
    private $white;
    private $yellow;
    private $green;
    private $red;

    /*
    * For each text entered by the user a specific can be specified,
    * the value is stored in these properties.
    */
    private $headerColour;
    private $bodyColour;
    private $footerColour;

   /*
   * The font type chosen by the user is specified here. 
   */
    private $headerFontType;
    private $bodyFontType;
    private $footerFontType;

    /*
    * The angle that the font will be tilted.
    */
    private $headerAngle;
    private $bodyAngle;
    private $footerAngle;

    /*
    * The font sizes can be specified by the users
    */
    private $headerFontSize;
    private $bodyFontSize;
    private $footerFontSize;
    

    function __construct($param)
    {
        $this->setImageProperties($param);
        $this->fonts();
        $this->image = imagecreatetruecolor($this->width, $this->height);
        //$this->colours();
        $this->assignFontType();
        $this->box();
        //$this->assignPosition();
    }

    function setImageProperties(array $param)
    {
       /*
       * Pass all the values ($text) passed as argument to the
       * constructor to the field property $this->text
       */
        $this->param = $param;

        /*
        * Assign the values to the corresponding class
        * properties that are required to be separate from the beginning.
        */
        if (isset($this->param['image_url'])) $this->imagePath = $this->param['image_url'];
        if (isset($this->param['title'])) $this->text['title'] = $this->param['title'];
        if (isset($this->param['body'])) $this->text['body'] = $this->param['body'];
        if (isset($this->param['footer'])) $this->text['footer'] = $this->param['footer'];
        if (isset($this->param['header_position'])) $this->titlePosition = $this->param['header_position'];
        if (isset($this->param['body_position'])) $this->bodyPosition = $this->param['body_position'];
        if (isset($this->param['footer_position'])) $this->footerPosition = $this->param['footer_position'];
        if (isset($this->param['header_colour'])) $this->headerColour = $this->param['header_colour'];
        if (isset($this->param['body_colour'])) $this->bodyColour = $this->param['body_colour'];
        if (isset($this->param['footer_colour'])) $this->footerColour = $this->param['footer_colour'];
        if (isset($this->param['hd_font_type'])) $this->headerFontType = $this->param['hd_font_type'];
        if (isset($this->param['bd_font_type'])) $this->bodyFontType = $this->param['bd_font_type'];
        if (isset($this->param['ft_font_type'])) $this->footerFontType = $this->param['ft_font_type'];
        if (isset($this->param['hd_font_size'])) {
            $this->headerFontSize = $this->param['hd_font_size'];
        } else {
            $this->headerFontSize = 20;
        }
        if (isset($this->param['bd_font_size'])) {
            $this->bodyFontSize = $this->param['bd_font_size'];
        } else {
            $this->bodyFontSize = 20;
        }
        if (isset($this->param['ft_font_size'])) {
            $this->footerFontSize = $this->param['ft_font_size'];
        } else {
            $this->footerFontSize = 20;
        }
        if (isset($this->param['hd_font_angle'])) {
            $this->headerAngle = $this->param['hd_font_angle'];
        } else {
            $this->headerAngle = 0;
        }
        if (isset($this->param['bd_font_angle'])) {
            $this->bodyAngle = $this->param['bd_font_angle'];
        } else {
            $this->bodyAngle = 0;
        }
        if (isset($this->param['ft_font_angle'])) {
            $this->footerAngle = $this->param['ft_font_angle'];
        } else {
            $this->footerAngle = 0;
        }
    }

    /*
     * The box to hold each text.
     * The box is drawn using the specified font size and style.
     */
    function box()
    {
        // Do a wordwrap before making the box.
        $this->wrappedHeader = wordwrap($this->text['title'], 30, "\n");
        $this->wrappedBody = wordwrap($this->text['body'], 35, "\n");
        $this->wrappedFooter = wordwrap($this->text['footer'], 20, "\n");

        // Assigns the bounding box to be used for the various texts to the class properties
        $this->headerBox = imagettfbbox($this->headerFontSize, $this->headerAngle, $this->headerFontType, $this->wrappedHeader);
        $this->bodyBox = imagettfbbox($this->bodyFontSize, $this->bodyAngle, $this->bodyFontType, $this->wrappedBody);
        $this->footerBox = imagettfbbox($this->footerFontSize, $this->footerAngle, $this->footerFontType, $this->wrappedFooter);
    }

    /*
     * The fonts require the font file to be loaded before they can be used. This function takes care of assigning the file path
     * This might seem to be more appropriate for the constructor, it's a matter of choice, so choose to put mine here. ;)
     */
    private function fonts()
    {
        $this->aria = app_base_dir() . '/public/resources/fonts/aria/aria.ttf';
        $this->franchise = app_base_dir() . '/public/resources/fonts/franchise/Franchise-Bold-hinted.ttf';
        $this->pacifico = app_base_dir() . '/public/resources/fonts/pacifico/Pacifico.ttf';
        $this->prisma = app_base_dir() . '/public/resources/fonts/prisma/Prisma.ttf';
    }

    /*
     *  Assign colours
     */
    private function colours()
    {
        $this->black = imagecolorallocate($this->image, 0, 0, 0);
        $this->white = imagecolorallocate($this->image, 255, 255, 255);
        $this->red = imagecolorallocate($this->image, 255, 0, 0);
        $this->yellow = imagecolorallocate($this->image, 255, 255, 0);
        $this->green = imagecolorallocate($this->image, 0, 100, 0);
    }

    /*
    *   Get the path of the image being written on 
    */
    function getImagePath()
    {
        if(isset($this->param['image'])) $this->imagePath = $this->param['image'];
        return $this->imagePath;
    }

    /*
     * Get the image file and check the dimensions.
     * Assign the values to class properties.
     */
    function resizeImage()
    {
        // Get the dimension of the original image as an array
        list($fileWidth, $fileHeight) = getimagesize($this->imagePath);

        // Check the ratio of the new image and reassign new width and height if necessary
        $ratio = $fileWidth / $fileHeight;

        if ($this->width / $this->height > $ratio) {
            $this->width = $this->height * $ratio;
        } else {
            $this->height = $this->width / $ratio;
        }

        // Resample
        $source = imagecreatefrompng($this->imagePath);
        $this->image = imagecreatetruecolor($this->width, $this->height);

        imagecopyresampled($this->image, $source, 0, 0, 0, 0, $this->width, $this->height, $fileWidth, $fileHeight);

        return $this->image;
    }  

    /*
    * The boxes made in box() and assigned to the corresponding field property is used here to 
    * calculate various positions for the text. There are nine possible positions in all
    * Ranging from topLeft() to bottomRight().
    */
    function topLeft()
    {
        // Retrieves the width and height which is used to set the X and Y coordinates.
         $x = $this->headerBox[0] ;
         $y = $this->headerBox[1] + 35;

        $this->titlePosition = array($x, $y);
        return $this->titlePosition;
    }

    function topMiddle()
    {
        // Retrieves the width and height which is used to set the X and Y coordinates.
        $x = (imagesx($this->image)/2) - ($this->headerBox[2]/2);
        $y = $this->headerBox[1] + 35;

        $this->titlePosition = array($x, $y);
        return $this->titlePosition;
    }

    function topRight()
    {
        // Retrieves the width and height which is used to set the X and Y coordinates.
        $x = imagesx($this->image) - $this->headerBox[2] - 25;
        $y = $this->headerBox[1] + 35;

        $this->titlePosition = array($x, $y);
        return $this->titlePosition;
    }

    function middleLeft()
    {
        // Retrieves the width and height which is used to set the X and Y coordinates.
        $x = $this->bodyBox[0] ;
        $y = (imagesy($this->image)/2) - (imagesy($this->image)/8);

        $this->bodyPosition = array($x, $y);
        return $this->bodyPosition;
    }

    function centre()
    {
        // Retrieves the width and height which is used to set the X and Y coordinates.
        $x = (imagesx($this->image)/2) - ($this->bodyBox[2]/2);
        $y = (imagesy($this->image)/2) - (imagesy($this->image)/8);
     
        $this->bodyPosition = array($x, $y);
        return $this->bodyPosition;
    }

    function middleRight()
    {
        // Retrieves the width and height which is used to set the X and Y coordinates.
        $x = imagesx($this->image) - $this->bodyBox[2] - 25;
        $y = (imagesy($this->image)/2) - (imagesy($this->image)/8);

        $this->bodyPosition = array($x, $y);
        return $this->bodyPosition;
    }

    function bottomLeft()
    {
        // Retrieves the width and height which is used to set the X and Y coordinates.
        $x = $this->footerBox[0] ;
        $y = (imagesy($this->image)/2) + (imagesy($this->image)/8);

        $this->footerPosition = array($x, $y);
        return $this->footerPosition;
    }

    function bottomCentre()
    {
       // Retrieves the width and height which is used to set the X and Y coordinates.
        $x = (imagesx($this->image)/2) - ($this->footerBox[2]/2);
        $y = (imagesy($this->image)/2) + (imagesy($this->image)/8);

        $this->footerPosition = array($x, $y);
        return $this->footerPosition;
    }

    function bottomRight()
    {
         // Retrieves the width and height which is used to set the X and Y coordinates.
        $x = imagesx($this->image) - $this->footerBox[2] - 5;
        $y = (imagesy($this->image)/2) + (imagesy($this->image)/8);

        $this->footerPosition = array($x, $y);
        return $this->footerPosition;
    }     

    /*
     * Generate random names for the image
     */
    function getRandomWord()
    {
        $randomwWord = substr(str_shuffle('abcdefghijklmnopqrstuvwxyz'), 0, 4);        
        $this->randomName = $randomwWord;
    }  

     /*
     *  Handles the logic to choose a particular colour.
     */
    public function assignColour()
    {
        $this->colours();

        if ($this->headerColour == "red") $this->headerColour = $this->red;
        elseif ($this->headerColour == "white") $this->headerColour = $this->white;
        elseif ($this->headerColour == "black") $this->headerColour = $this->black;
        elseif ($this->headerColour == "yellow") $this->headerColour = $this->yellow;
        elseif ($this->headerColour == "green") $this->headerColour = $this->green;
        else $this->headerColour = $this->white;

        if ($this->bodyColour == "red") $this->bodyColour = $this->red;
        elseif ($this->bodyColour == "white") $this->bodyColour = $this->white;
        elseif ($this->bodyColour == "black") $this->bodyColour = $this->black;
        elseif ($this->bodyColour == "yellow") $this->bodyColour = $this->yellow;
        elseif ($this->bodyColour == "green") $this->bodyColour = $this->green;
        else $this->bodyColour = $this->white;

        if ($this->footerColour == "red") $this->footerColour = $this->red;
        elseif ($this->footerColour == "white") $this->footerColour = $this->white;
        elseif ($this->footerColour == "black") $this->footerColour = $this->black;
        elseif ($this->footerColour == "yellow") $this->footerColour = $this->yellow;
        elseif ($this->footerColour == "green") $this->footerColour = $this->green;
        else $this->footerColour = $this->white;
   }    

   function assignFontType()
   {
       if ($this->headerFontType == "aria") $this->headerFontType = $this->aria;
       elseif ($this->headerFontType == "franchise") $this->headerFontType = $this->franchise;
       elseif ($this->headerFontType == "pacifico") $this->headerFontType = $this->pacifico;
       else $this->headerFontType = $this->prisma;

       if ($this->bodyFontType == "aria") $this->bodyFontType = $this->aria;
       elseif ($this->bodyFontType == "franchise") $this->bodyFontType = $this->franchise;
       elseif ($this->bodyFontType == "pacifico") $this->bodyFontType = $this->pacifico;
       else $this->bodyFontType = $this->prisma;

       if ($this->footerFontType == "aria") $this->footerFontType = $this->aria;
       elseif ($this->footerFontType == "franchise") $this->footerFontType = $this->franchise;
       elseif ($this->footerFontType == "pacifico") $this->footerFontType = $this->pacifico;
       else $this->footerFontType = $this->prisma;
   }   

    /*
     * Check the positions chosen by the user for the various texts
     */
    function assignPosition()
    {        
        if (!empty($this->titlePosition)) {
            if ($this->titlePosition == "left") $this->titlePosition = $this->topLeft();
            elseif ($this->titlePosition == "centre") $this->titlePosition = $this->topMiddle();
            elseif ($this->titlePosition == "right") $this->titlePosition = $this->topRight();
            else {
                echo "Assign a position for the header";
            }
        }
        if (!empty($this->bodyPosition)) {
            if ($this->bodyPosition == "left") $this->bodyPosition = $this->middleLeft();
            elseif ($this->bodyPosition == "centre") $this->bodyPosition = $this->centre();
            elseif ($this->bodyPosition == "right") $this->bodyPosition = $this->middleRight();
            else {
                echo "Assign a position for the body";
            }
        }
        if (!empty($this->footerPosition)) {
            if ($this->footerPosition == "left") $this->footerPosition = $this->bottomLeft();
            elseif ($this->footerPosition == "centre") $this->footerPosition = $this->bottomCentre();
            elseif ($this->footerPosition == "right") $this->footerPosition = $this->bottomRight();
            else {
                echo "Assign a position for the signature";
            }
        } else {
            echo "Please choose a position to display your text";
        }
    }

    function writeTextOnPic()
    {
        $this->resizeImage();

        $this->getRandomWord();

        $this->assignColour();

      //  $image = imagecreatefrompng($this->imagePath);

        // Get all the coordinates required to write text.
        list($x, $y) = $this->titlePosition;
        imagettftext($this->image, $this->headerFontSize, $this->headerAngle, $x, $y, $this->headerColour, $this->headerFontType, $this->wrappedHeader);

        list($x, $y) = $this->bodyPosition;
        imagettftext($this->image, $this->bodyFontSize, $this->bodyAngle, $x, $y, $this->bodyColour, $this->bodyFontType, $this->wrappedBody);

        list($x, $y) = $this->footerPosition;
        imagettftext($this->image, $this->footerFontSize, $this->footerAngle, $x, $y, $this->headerColour, $this->headerFontType, $this->wrappedFooter);

        // Save the file and return to the user.
        $storagePath = app_base_dir().'/file_storage/cards/'.$this->randomName.'.png';
        return imagepng($this->image, $storagePath);
    }

    /*
    * Since text can either be on a picture or on a colour canvas.
    * This method is called to write texts on a colour canvas.
    */
    function writeTextOnColourCanvas()
    {
        $backgroundColor = imagecolorallocate($this->image, 222,184,135);
        imagefill($this->image, 0, 0, $backgroundColor);

        // Generate a random word for saving the image.
        $this->getRandomWord();

        // Determine the colour the user chose for various texts
        $this->assignColour();

        /*
        * Make $x and $y references to the coordinates of each text position
        */
        // Set header text position and write
        list($x, $y) = $this->titlePosition;
        imagettftext($this->image, $this->headerFontSize, $this->headerAngle, $x, $y, $this->headerColour, $this->headerFontType, $this->wrappedHeader);

        // Set body text position and write
        list($x, $y) = $this->bodyPosition;
        imagettftext($this->image, $this->bodyFontSize, $this->bodyAngle, $x, $y, $this->bodyColour, $this->bodyFontType, $this->wrappedBody);

        // Set footer text position and write
        list($x, $y) = $this->footerPosition;
        imagettftext($this->image, $this->footerFontSize, $this->footerAngle, $x, $y, $this->footerColour, $this->footerFontType, $this->wrappedFooter);       

        // Save the file and return to the user.
        $storagePath = app_base_dir().'/file_storage/cards/'.$this->randomName.'.png';
        return imagepng($this->image, $storagePath);        
    }
}